// Generated by BUCKLESCRIPT VERSION 3.1.0, PLEASE EDIT WITH CARE
'use strict';


var $$Map = /* module */[];

var mainMap = [/* None */0];

ymaps.ready((function () {
        console.log("maps are ready");
        var m = new (ymaps.Map)("mapHolder", {
              center: /* tuple */[
                55.0,
                37.0
              ],
              zoom: 10
            });
        mainMap[0] = /* Some */[m];
        return /* () */0;
      }));

exports.$$Map = $$Map;
exports.mainMap = mainMap;
/*  Not a pure module */
